[package]
name = "simx"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"
publish = false

[dependencies]
getrandom = "0.2.10"
serde = { version = "1.0.164", features = ["derive"] }
uuid = { version = "1.3.4", features = ["serde", "v4"] }

[dev-dependencies]
serde_json = "1.0.97"
